server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/fundoo/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userfallback

        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/fundoo/note/**
          filters:
            - name: CircuitBreaker
              args:
                name: note-service
                fallbackuri: forward:/notefallback

management:
  endpoint:
    web:
      exposure:
        include:hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutMilliseconds:5000



